const { ROLES } = require('./roles');

/**
 * Granular system permissions
 */
const PERMISSIONS = Object.freeze({
  // User Management
  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',

  // Location Hierarchy Permissions (Phase 2)
  STATE_READ: 'STATE_READ',
  STATE_CREATE: 'STATE_CREATE',
  STATE_UPDATE: 'STATE_UPDATE',
  STATE_DELETE: 'STATE_DELETE',

  DIVISION_READ: 'DIVISION_READ',
  DIVISION_CREATE: 'DIVISION_CREATE',
  DIVISION_UPDATE: 'DIVISION_UPDATE',
  DIVISION_DELETE: 'DIVISION_DELETE',

  REGION_READ: 'REGION_READ',
  REGION_CREATE: 'REGION_CREATE',
  REGION_UPDATE: 'REGION_UPDATE',
  REGION_DELETE: 'REGION_DELETE',

  DISTRICT_READ: 'DISTRICT_READ',
  DISTRICT_CREATE: 'DISTRICT_CREATE',
  DISTRICT_UPDATE: 'DISTRICT_UPDATE',
  DISTRICT_DELETE: 'DISTRICT_DELETE',

  TALUKA_READ: 'TALUKA_READ',
  TALUKA_CREATE: 'TALUKA_CREATE',
  TALUKA_UPDATE: 'TALUKA_UPDATE',
  TALUKA_DELETE: 'TALUKA_DELETE',

  VILLAGE_CITY_READ: 'VILLAGE_CITY_READ',
  VILLAGE_CITY_CREATE: 'VILLAGE_CITY_CREATE',
  VILLAGE_CITY_UPDATE: 'VILLAGE_CITY_UPDATE',
  VILLAGE_CITY_DELETE: 'VILLAGE_CITY_DELETE',

  AREA_LOCALITY_READ: 'AREA_LOCALITY_READ',
  AREA_LOCALITY_CREATE: 'AREA_LOCALITY_CREATE',
  AREA_LOCALITY_UPDATE: 'AREA_LOCALITY_UPDATE',
  AREA_LOCALITY_DELETE: 'AREA_LOCALITY_DELETE',

  // Mosque Management Permissions (Phase 3)
  // NOTE: Study Center fields are now merged into Mosque, so the old
  // STUDY_CENTER_*/CENTER_* permissions have been removed. Anything that
  // previously required CENTER_READ/CENTER_WRITE for study-center-specific
  // data should now just use MOSQUE_READ/MOSQUE_UPDATE.
  MOSQUE_READ: 'MOSQUE_READ',
  MOSQUE_CREATE: 'MOSQUE_CREATE',
  MOSQUE_UPDATE: 'MOSQUE_UPDATE',
  MOSQUE_DELETE: 'MOSQUE_DELETE',
  MOSQUE_WRITE: 'MOSQUE_WRITE', // Alias for write compatibility

  // Students & Academics (Phase 5+ readiness)
  STUDENT_READ: 'STUDENT_READ',
  STUDENT_WRITE: 'STUDENT_WRITE',
  ATTENDANCE_MARK: 'ATTENDANCE_MARK',
  TEST_WRITE: 'TEST_WRITE',
  REPORT_VIEW: 'REPORT_VIEW',

  // Teacher / Staff Management (Phase 5+)
  TEACHER_READ: 'TEACHER_READ',
  TEACHER_CREATE: 'TEACHER_CREATE',
  TEACHER_UPDATE: 'TEACHER_UPDATE',
  TEACHER_DELETE: 'TEACHER_DELETE',
  TEACHER_ATTENDANCE_MANAGE: 'TEACHER_ATTENDANCE_MANAGE',
  TEACHER_ATTENDANCE_READ: 'TEACHER_ATTENDANCE_READ',
  TEACHER_REPORT_MANAGE: 'TEACHER_REPORT_MANAGE',
  TEACHER_REPORT_READ: 'TEACHER_REPORT_READ',

  // Coordinator Management (mirrors Teacher)
  COORDINATOR_READ: 'COORDINATOR_READ',
  COORDINATOR_CREATE: 'COORDINATOR_CREATE',
  COORDINATOR_UPDATE: 'COORDINATOR_UPDATE',
  COORDINATOR_DELETE: 'COORDINATOR_DELETE',
  COORDINATOR_ATTENDANCE_MANAGE: 'COORDINATOR_ATTENDANCE_MANAGE',
  COORDINATOR_ATTENDANCE_READ: 'COORDINATOR_ATTENDANCE_READ'
});

const ALL_LOCATION_READ = [
  PERMISSIONS.STATE_READ,
  PERMISSIONS.DIVISION_READ,
  PERMISSIONS.REGION_READ,
  PERMISSIONS.DISTRICT_READ,
  PERMISSIONS.TALUKA_READ,
  PERMISSIONS.VILLAGE_CITY_READ,
  PERMISSIONS.AREA_LOCALITY_READ,
  PERMISSIONS.MOSQUE_READ
];

const ALL_LOCATION_PERMISSIONS = [
  ...ALL_LOCATION_READ,
  PERMISSIONS.STATE_CREATE,
  PERMISSIONS.STATE_UPDATE,
  PERMISSIONS.STATE_DELETE,
  PERMISSIONS.DIVISION_CREATE,
  PERMISSIONS.DIVISION_UPDATE,
  PERMISSIONS.DIVISION_DELETE,
  PERMISSIONS.REGION_CREATE,
  PERMISSIONS.REGION_UPDATE,
  PERMISSIONS.REGION_DELETE,
  PERMISSIONS.DISTRICT_CREATE,
  PERMISSIONS.DISTRICT_UPDATE,
  PERMISSIONS.DISTRICT_DELETE,
  PERMISSIONS.TALUKA_CREATE,
  PERMISSIONS.TALUKA_UPDATE,
  PERMISSIONS.TALUKA_DELETE,
  PERMISSIONS.VILLAGE_CITY_CREATE,
  PERMISSIONS.VILLAGE_CITY_UPDATE,
  PERMISSIONS.VILLAGE_CITY_DELETE,
  PERMISSIONS.AREA_LOCALITY_CREATE,
  PERMISSIONS.AREA_LOCALITY_UPDATE,
  PERMISSIONS.AREA_LOCALITY_DELETE,
  PERMISSIONS.MOSQUE_CREATE,
  PERMISSIONS.MOSQUE_UPDATE,
  PERMISSIONS.MOSQUE_DELETE,
  PERMISSIONS.MOSQUE_WRITE
];

/**
 * Role to Permission mapping matrix
 */
const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  // NOTE: DISTRICT_ADMIN gets DIVISION_READ and REGION_READ automatically
  // via ...ALL_LOCATION_READ below (same as STATE_READ) — divisions and
  // regions sit above districts, so this role is kept read-only on both.
  // Add PERMISSIONS.DIVISION_UPDATE / REGION_UPDATE here if you want
  // District Admins to be able to edit (not just view) them.
  [ROLES.DISTRICT_ADMIN]: [
    PERMISSIONS.USER_READ,
    ...ALL_LOCATION_READ,
    PERMISSIONS.DISTRICT_UPDATE,
    PERMISSIONS.TALUKA_CREATE,
    PERMISSIONS.TALUKA_UPDATE,
    PERMISSIONS.TALUKA_DELETE,
    PERMISSIONS.VILLAGE_CITY_CREATE,
    PERMISSIONS.VILLAGE_CITY_UPDATE,
    PERMISSIONS.VILLAGE_CITY_DELETE,
    PERMISSIONS.AREA_LOCALITY_CREATE,
    PERMISSIONS.AREA_LOCALITY_UPDATE,
    PERMISSIONS.AREA_LOCALITY_DELETE,
    PERMISSIONS.MOSQUE_CREATE,
    PERMISSIONS.MOSQUE_UPDATE,
    PERMISSIONS.MOSQUE_DELETE,
    PERMISSIONS.MOSQUE_WRITE,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_WRITE,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.TEST_WRITE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.TEACHER_CREATE,
    PERMISSIONS.TEACHER_UPDATE,
    PERMISSIONS.TEACHER_DELETE,
    PERMISSIONS.TEACHER_ATTENDANCE_MANAGE,
    PERMISSIONS.TEACHER_ATTENDANCE_READ,
    PERMISSIONS.TEACHER_REPORT_MANAGE,
    PERMISSIONS.TEACHER_REPORT_READ,
    PERMISSIONS.COORDINATOR_READ,
    PERMISSIONS.COORDINATOR_CREATE,
    PERMISSIONS.COORDINATOR_UPDATE,
    PERMISSIONS.COORDINATOR_DELETE,
    PERMISSIONS.COORDINATOR_ATTENDANCE_MANAGE,
    PERMISSIONS.COORDINATOR_ATTENDANCE_READ
  ],

  [ROLES.MOSQUE_CENTER_ADMIN]: [
    ...ALL_LOCATION_READ,
    PERMISSIONS.MOSQUE_READ,
    PERMISSIONS.MOSQUE_UPDATE,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_WRITE,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.TEST_WRITE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.TEACHER_CREATE,
    PERMISSIONS.TEACHER_UPDATE,
    PERMISSIONS.TEACHER_DELETE,
    PERMISSIONS.TEACHER_ATTENDANCE_MANAGE,
    PERMISSIONS.TEACHER_ATTENDANCE_READ,
    PERMISSIONS.TEACHER_REPORT_MANAGE,
    PERMISSIONS.TEACHER_REPORT_READ,
    PERMISSIONS.COORDINATOR_READ,
    PERMISSIONS.COORDINATOR_CREATE,
    PERMISSIONS.COORDINATOR_UPDATE,
    PERMISSIONS.COORDINATOR_DELETE,
    PERMISSIONS.COORDINATOR_ATTENDANCE_MANAGE,
    PERMISSIONS.COORDINATOR_ATTENDANCE_READ
  ],

  [ROLES.TEACHER]: [
    ...ALL_LOCATION_READ,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_WRITE,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.TEST_WRITE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.TEACHER_ATTENDANCE_READ,
    PERMISSIONS.TEACHER_REPORT_MANAGE,
    PERMISSIONS.TEACHER_REPORT_READ
  ],

  [ROLES.DATA_ENTRY_OPERATOR]: [
    ...ALL_LOCATION_READ,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_WRITE,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.TEACHER_ATTENDANCE_MANAGE,
    PERMISSIONS.TEACHER_ATTENDANCE_READ,
    PERMISSIONS.COORDINATOR_READ,
    PERMISSIONS.COORDINATOR_ATTENDANCE_MANAGE,
    PERMISSIONS.COORDINATOR_ATTENDANCE_READ
  ]
});

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS
};